### ISSUE TITLE
Facebook albums don't work

### ISSUE THREAD

**Issue by Daniel15** [vickyg3/social-photos#2]
GET to load album list (http://socialphotos.net/album_list.php?id=1&pane=1) returns a null response
GET for creating album (http://socialphotos.net/create_album.php?id=1&albumtitle=Test+Social+Photos&albumcaption=) "succeeds" but returns `albumid: null`

**Comment by vickyg3** [comment]
it looks like i need to submit the app for approval with facebook and only then it will have access to album. i will try doing it sometime soon. thanks!

**Comment by vickyg3** [comment]
resolved now.
