### ISSUE TITLE
Social Photos Tag on Facebook Album directs to .com, not .net

### ISSUE THREAD

**Issue by avrampenner** [vickyg3/social-photos#56]
As you can see in the image, when mousing over Social Photos! tag on the album, the hyperlink is to socialphotos.com, not socialphotos.net.  Socialphotos.com redirects to network-alerts.info, a malicious website with a popup warning loop.

![image](https://cloud.githubusercontent.com/assets/17415711/13231126/87792ebe-d965-11e5-820c-f59ccde28add.png)

![image](https://cloud.githubusercontent.com/assets/17415711/13231184/d07dfaae-d965-11e5-9acc-195bf661b4d3.png)

**Comment by vickyg3** [comment]
thanks for reporting. i have fixed it now.

**Comment by avrampenner** [comment]
Cool, thanks!
