### ISSUE TITLE
Error when I try to login to instagram

### ISSUE THREAD

**Issue by thomaswhite** [vickyg3/social-photos#60]
{"code": 403, "error_type": "OAuthForbiddenException", "error_message": "You are not a sandbox user of this client"}

**Comment by vickyg3** [comment]
It looks like instagram put the app in sandbox mode. I've initiated a submission request to go live. This will be fixed then. Thanks for pointing it out!

**Comment by vickyg3** [comment]
Instagram has approved the app. This issue is now fixed.
