### ISSUE TITLE
Enhancement suggestion: using client-side javascript for sync service

### ISSUE THREAD

**Issue by Yehonal** [vickyg3/social-photos#62]
Hello

I love this project and service! i've developed something similar few years ago to sync my google+ albums with facebook.

i've read that you are offering a 100% free service and with privacy in mind.
However i've seen that you're using mostly php for all sync processes. My old project has been written totally in client-side javascript with cookie / localstorage to save preferences.

This would allow you to:

1) make all processes client-side , without any complain about privacy issues.
2) redistributing the application as a downloadable app
3) use some free hosting service, such as google app engine

Of course the takeaway service can remain server-side

**Comment by vickyg3** [comment]
Thanks for the suggestion.

The whole point of social photos is to transfer photos from one service to another _without_ using your bandwidth. This is especially useful if you are in a network connection which has restricted bandwidth.

**Comment by Yehonal** [comment]
Client side javascript doesn't use your bandwidth, in fact you just ask
facebook to retrieve photos from drive,  via javascript instead of php. But
the uploading process never pass from your bandwidth. You misunderstood.

If you want i can send you my script as example.

Il 26/Lug/2016 01:11, "Vignesh Venkat" notifications@github.com ha
scritto:

**Comment by Yehonal** [comment]
Client side javascript doesn't use your bandwidth, in fact you just ask
facebook to retrieve photos from drive,  via javascript instead of php. But
the uploading process never pass from your bandwidth. You misunderstood.

If you want i can send you my script as example.

Il 26/Lug/2016 01:11, "Vignesh Venkat" notifications@github.com ha
scritto:

Thanks for the suggestion.

The whole point of social photos is to transfer photos from one service to
another _without_ using your bandwidth. This is especially useful if you
are in a network connection which has restricted bandwidth.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/vickyg3/social-photos/issues/62#issuecomment-235114432,
or mute the thread

**Comment by vickyg3** [comment]
While that may be true for facebook which allows you to upload pictures by passing in a URL, other services do not allow such an upload mechanism. So this cannot be fully replicated without using your bandwidth in javascript.
