### ISSUE TITLE
Can't login to any social networks

### ISSUE THREAD

**Issue by qwandor** [vickyg3/social-photos#63]
As of a week or two ago, I am no longer able to log in to Social Photos with any of the social network options. No matter whether I select Google+ or Facebook, it takes me to login and authorize with the social network site if I haven't yet, but when it takes me back to the Social Photos page it's back to the initial state and not signed in. This happens on both Chrome and Firefox on both Mac OS and Linux.

**Comment by qwandor** [comment]
Does this work for anyone? Because as far as I can see socialphotos has been completely broken for at least a month. )-:

**Comment by YAizenman** [comment]
Not for me!

**Comment by qwandor** [comment]
Curiously, if I set up social-photos on my own server the login seems to work fine, though other things are broken later in the process. So the bug seems to be something to do with the server set-up rather than the code itself.

**Comment by vickyg3** [comment]
Sorry guys. I will take a look at the server side shortly.

**Comment by vickyg3** [comment]
The server ran out of disk space. It should be working now.
