### ISSUE TITLE
Grey

### ISSUE THREAD

**Issue by toralux** [vickyg3/social-photos#67]
I just tried to transfer 53 photos from Flickr to Facebook and only one photo was successfully transferred, all the others are only partially transferred, from about 20% to 80% are lost, just greyed out by Facebook. Can you please look into this issue? I will donate! Except from that (and that only title is transfered - not combination of title and description) the service is the best that is on all of internet! Cheers! :):)

**Comment by vickyg3** [comment]
Same as #66
