### ISSUE TITLE
Flickr

### ISSUE THREAD

**Issue by toralux** [vickyg3/social-photos#68]
Log in to Flickr as source don't seem to work and don't show albums any more. I tried several times for a few days from different computers/browsers. Facebook as destination shows albums immediately.

![image](https://cloud.githubusercontent.com/assets/422309/22353739/43c31c16-e422-11e6-80c0-8f6e77edc16d.png)

**Comment by toralux** [comment]
I finally was able to login to both Flickr and Facebook, so Flickr-login was not the issue, but after 30 minutes no album i created on Facebook and the screen still shows: 

![image](https://cloud.githubusercontent.com/assets/422309/22372327/61863e52-e49c-11e6-8400-3eef497e400e.png)

**Comment by toralux** [comment]
Finally it started to transfer but will not transfer full pictures, just about half of dem (same as issue #66). It looks like the server has to little resources, not enough memory? How can we fix this - donate more?

![image](https://cloud.githubusercontent.com/assets/422309/22372759/cc32d376-e49e-11e6-996e-2b6d911be2ff.png)

**Comment by vickyg3** [comment]
Please see the last comment on #66.

Same as #66
