### ISSUE TITLE
Corruption in uploading photos 

### ISSUE THREAD

**Issue by firebird7102** [vickyg3/social-photos#69]
Great software - easy to use and efficient however photos seem to be corrupted going from google photos to facebook album see screenshot below.

<img width="215" alt="screen shot 2017-01-30 at 10 10 15 pm" src="https://cloud.githubusercontent.com/assets/25431044/22421002/43caa8ea-e739-11e6-879b-49ed7a8ddb8f.png">

**Comment by vickyg3** [comment]
Same as #66
