### ISSUE TITLE
Google Safe Browsing marks socialphotos as unsafe

### ISSUE THREAD

**Issue by johnclark456** [vickyg3/social-photos#72]
When attempting to browse the socialphotos.net on a Chromebook with Chrome 57 results in the following error:

![screenshot 2017-04-16 at 10 16 36 pm](https://cloud.githubusercontent.com/assets/10817941/25074451/c9ab5c3a-22f2-11e7-9725-1e9e30315062.png)

**Comment by qwandor** [comment]
I get this too.

**Comment by vickyg3** [comment]
I see a weird issue on a sub-domain that has never existed. I've submitted a review with google webmaster tools. I'll update once i hear back from them.

As always, thanks for pointing this out.

**Comment by vickyg3** [comment]
Google reviewed it and the warning should be gone now. It works for me as intended now. Thank you!
